[package]
name = "rocket-demo"
version = "0.1.0"
edition = "2021"
author = "Sverre Johann Bjørke"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ['json']

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.2"
features = ["tera"]